const setThemeLight = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#555555')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#555555')
  style.setProperty('--theme_notes_background_color', '#EEEEEF')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', 'none')

  style.setProperty('--theme_link_color', '#555555')
  style.setProperty('--theme_link_background_color', '#EEEEEF')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'underline')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', 'none')
  style.setProperty('--theme_link_box_shadow_active', 'none')
  style.setProperty('--theme_link_filter', 'brightness(95%)')

  style.setProperty('--theme_text_input_color', '#555555')
  style.setProperty('--theme_text_input_background_color', '#EEEEEF')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', 'none')
  style.setProperty('--theme_text_input_box_shadow_active', 'none')

  style.setProperty('--theme_button_color', '#EEEEEF')
  style.setProperty('--theme_button_background_color', '#555555')
  style.setProperty('--theme_button_box_shadow', 'none')
  style.setProperty('--theme_button_box_shadow_active', 'none')

  style.setProperty('--theme_icon_button_color', '#555555')
  style.setProperty('--theme_icon_button_background_color', '#EEEEEF')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', 'none')
  style.setProperty('--theme_icon_button_color_down', '#EEEEEF')
  style.setProperty('--theme_icon_button_background_color_down', '#555555')
  style.setProperty('--theme_icon_button_box_shadow_down', 'none')

  style.setProperty('--theme_background_color', '#EEEEEF')
  style.setProperty('--theme_background_color_menu_bar', '#EEEEEF')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #222222 0%, #090979 35%, #0099b8 100%)')
  style.setProperty('--theme_background_color_status_bar', '#EEEEEF')
  style.setProperty('--theme_background_color_button_down', '#EEEEEF')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#0000FF')
  style.setProperty('--theme_text_color_label', '#555555')
  style.setProperty('--theme_text_color_field', '#555555')
  style.setProperty('--theme_text_color_button_down', '#555555')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid white')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', '#555555')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', 'none')
  style.setProperty('--theme_box_shadow_image_button', 'none')
  style.setProperty('--theme_box_shadow_image_button_active', 'none')
  style.setProperty('--theme_box_shadow_small', 'none')
  style.setProperty('--theme_box_shadow_small_active', 'none')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', 'rgba(0,51,153,0.3)')
  style.setProperty('--theme_secondary_power_set', 'rgba(153,0,0,0.3)')
  style.setProperty('--theme_pool_power_set', 'rgba(255,153,0,0.3)')
  style.setProperty('--theme_epic_power_set', 'rgba(153,0,0,0.3)')
  style.setProperty('--theme_inherent_power_set', 'rgba(51,102,0,0.3)')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

const setThemeDark = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#EEEEEF')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#EEEEEF')
  style.setProperty('--theme_notes_background_color', '#555555')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', 'none')

  style.setProperty('--theme_link_color', '#EEEEEF')
  style.setProperty('--theme_link_background_color', '555555#')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'underline')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', 'none')
  style.setProperty('--theme_link_box_shadow_active', 'none')
  style.setProperty('--theme_link_filter', 'brightness(150%)')

  style.setProperty('--theme_text_input_color', '#555555')
  style.setProperty('--theme_text_input_background_color', '#EEEEEF')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', 'none')
  style.setProperty('--theme_text_input_box_shadow_active', 'none')

  style.setProperty('--theme_button_color', '#555555')
  style.setProperty('--theme_button_background_color', '#EEEEEF')
  style.setProperty('--theme_button_box_shadow', 'none')
  style.setProperty('--theme_button_box_shadow_active', 'none')

  style.setProperty('--theme_icon_button_color', '#EEEEEF')
  style.setProperty('--theme_icon_button_background_color', '#555555')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', 'none')
  style.setProperty('--theme_icon_button_color_down', '#555555')
  style.setProperty('--theme_icon_button_background_color_down', '#EEEEEF')
  style.setProperty('--theme_icon_button_box_shadow_down', 'none')

  style.setProperty('--theme_background_color', '#555555')
  style.setProperty('--theme_background_color_menu_bar', '#555555')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #272727 0%, #444444 35%, #555555 100%)')
  style.setProperty('--theme_background_color_status_bar', '#555555')
  style.setProperty('--theme_background_color_button_down', '#EEEEEF')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#0000FF')
  style.setProperty('--theme_text_color_label', '#EEEEEF')
  style.setProperty('--theme_text_color_field', '#EEEEEF')
  style.setProperty('--theme_text_color_button_down', '#555555')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid white')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', 'transparent')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', 'none')
  style.setProperty('--theme_box_shadow_image_button', 'none')
  style.setProperty('--theme_box_shadow_image_button_active', 'none')
  style.setProperty('--theme_box_shadow_small', 'none')
  style.setProperty('--theme_box_shadow_small_active', 'none')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', '#6495ED')
  style.setProperty('--theme_secondary_power_set', '#FF4500')
  style.setProperty('--theme_pool_power_set', '#FFA500')
  style.setProperty('--theme_epic_power_set', '#FFFFBF')
  style.setProperty('--theme_inherent_power_set', '#3CB371')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

const setThemeHero = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#FFCC66')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#FFCC66')
  style.setProperty('--theme_notes_background_color', '#003366')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', 'none')

  style.setProperty('--theme_link_color', '#FFCC66')
  style.setProperty('--theme_link_background_color', '#003366')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'underline')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', 'none')
  style.setProperty('--theme_link_box_shadow_active', 'none')
  style.setProperty('--theme_link_filter', 'brightness(150%)')

  style.setProperty('--theme_text_input_color', '#003366')
  style.setProperty('--theme_text_input_background_color', '#FFCC66')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', 'none')
  style.setProperty('--theme_text_input_box_shadow_active', 'none')

  style.setProperty('--theme_button_color', '#003366')
  style.setProperty('--theme_button_background_color', '#FFCC66')
  style.setProperty('--theme_button_box_shadow', 'none')
  style.setProperty('--theme_button_box_shadow_active', 'none')

  style.setProperty('--theme_icon_button_color', '#FFCC66')
  style.setProperty('--theme_icon_button_background_color', '#003366')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', 'none')
  style.setProperty('--theme_icon_button_color_down', '#003366')
  style.setProperty('--theme_icon_button_background_color_down', '#FFCC66')
  style.setProperty('--theme_icon_button_box_shadow_down', 'none')

  style.setProperty('--theme_background_color', '#003366')
  style.setProperty('--theme_background_color_menu_bar', '#003366')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #0099b8 0%, #090979 35%, #020024 100%)')
  style.setProperty('--theme_background_color_status_bar', '#003366')
  style.setProperty('--theme_background_color_button_down', '#FFCC66')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#FFCC66')
  style.setProperty('--theme_text_color_label', '#FFCC66')
  style.setProperty('--theme_text_color_field', '#FFCC66')
  style.setProperty('--theme_text_color_button_down', '#003366')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid FFCC00')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', '#003366')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', 'none')
  style.setProperty('--theme_box_shadow_image_button', 'none')
  style.setProperty('--theme_box_shadow_image_button_active', 'none')
  style.setProperty('--theme_box_shadow_small', 'none')
  style.setProperty('--theme_box_shadow_small_active', 'none')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', '#000080')
  style.setProperty('--theme_secondary_power_set', '#FF2400')
  style.setProperty('--theme_pool_power_set', '#FF9900')
  style.setProperty('--theme_epic_power_set', '#FFFFBF')
  style.setProperty('--theme_inherent_power_set', '#00CC00')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

const setThemeVillian = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#f5efef')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#f5efef')
  style.setProperty('--theme_notes_background_color', '#810000')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', 'none')

  style.setProperty('--theme_link_color', '#f5efef')
  style.setProperty('--theme_link_background_color', '#810000')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'underline')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', 'none')
  style.setProperty('--theme_link_box_shadow_active', 'none')
  style.setProperty('--theme_link_filter', 'brightness(150%)')

  style.setProperty('--theme_text_input_color', '#810000')
  style.setProperty('--theme_text_input_background_color', '#f5efef')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', 'none')
  style.setProperty('--theme_text_input_box_shadow_active', 'none')

  style.setProperty('--theme_button_color', '#810000')
  style.setProperty('--theme_button_background_color', '#f5efef')
  style.setProperty('--theme_button_box_shadow', 'none')
  style.setProperty('--theme_button_box_shadow_active', 'none')

  style.setProperty('--theme_icon_button_color', '#f5efef')
  style.setProperty('--theme_icon_button_background_color', '#810000')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', 'none')
  style.setProperty('--theme_icon_button_color_down', '#810000')
  style.setProperty('--theme_icon_button_background_color_down', '#f5efef')
  style.setProperty('--theme_icon_button_box_shadow_down', 'none')

  style.setProperty('--theme_background_color', '#810000')
  style.setProperty('--theme_background_color_menu_bar', '#810000')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #240002 0%, #790909 35%, #b80900 100%)')
  style.setProperty('--theme_background_color_status_bar', '#810000')
  style.setProperty('--theme_background_color_button_down', '#f5efef')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#f5efef')
  style.setProperty('--theme_text_color_label', '#f5efef')
  style.setProperty('--theme_text_color_field', '#f5efef')
  style.setProperty('--theme_text_color_button_down', '#810000')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid FFCC00')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', '#810000')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', 'none')
  style.setProperty('--theme_box_shadow_image_button', 'none')
  style.setProperty('--theme_box_shadow_image_button_active', 'none')
  style.setProperty('--theme_box_shadow_small', 'none')
  style.setProperty('--theme_box_shadow_small_active', 'none')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', '#07689f')
  style.setProperty('--theme_secondary_power_set', '#FF2400')
  style.setProperty('--theme_pool_power_set', '#FFA500')
  style.setProperty('--theme_epic_power_set', '#FFFFBF')
  style.setProperty('--theme_inherent_power_set', '#3CB371')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

const setThemeGamma = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#FFCF79')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#FFCF79')
  style.setProperty('--theme_notes_background_color', '#2C6700')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', 'none')

  style.setProperty('--theme_link_color', '#FFCF79')
  style.setProperty('--theme_link_background_color', '#2C6700')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'underline')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', 'none')
  style.setProperty('--theme_link_box_shadow_active', 'none')
  style.setProperty('--theme_link_filter', 'brightness(150%)')

  style.setProperty('--theme_text_input_color', '#2C6700')
  style.setProperty('--theme_text_input_background_color', '#FFCF79')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', 'none')
  style.setProperty('--theme_text_input_box_shadow_active', 'none')

  style.setProperty('--theme_button_color', '#2C6700')
  style.setProperty('--theme_button_background_color', '#FFCF79')
  style.setProperty('--theme_button_box_shadow', 'none')
  style.setProperty('--theme_button_box_shadow_active', 'none')

  style.setProperty('--theme_icon_button_color', '#FFCF79')
  style.setProperty('--theme_icon_button_background_color', '#2C6700')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', 'none')
  style.setProperty('--theme_icon_button_color_down', '#2C6700')
  style.setProperty('--theme_icon_button_background_color_down', '#FFCF79')
  style.setProperty('--theme_icon_button_box_shadow_down', 'none')

  style.setProperty('--theme_background_color', '#2C6700')
  style.setProperty('--theme_background_color_menu_bar', '#2C6700')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #022400 0%, #097009 35%, #00b809 100%)')
  style.setProperty('--theme_background_color_status_bar', '#2C6700')
  style.setProperty('--theme_background_color_button_down', '#FFCF79')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#FFCF79')
  style.setProperty('--theme_text_color_label', '#FFCF79')
  style.setProperty('--theme_text_color_field', '#FFCF79')
  style.setProperty('--theme_text_color_button_down', '#2C6700')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid FFCF79')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', '#2C6700')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', 'none')
  style.setProperty('--theme_box_shadow_image_button', 'none')
  style.setProperty('--theme_box_shadow_image_button_active', 'none')
  style.setProperty('--theme_box_shadow_small', 'none')
  style.setProperty('--theme_box_shadow_small_active', 'none')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', '#003399')
  style.setProperty('--theme_secondary_power_set', '#FF2400')
  style.setProperty('--theme_pool_power_set', '#FF9900')
  style.setProperty('--theme_epic_power_set', '#FFFFBF')
  style.setProperty('--theme_inherent_power_set', '#00CC00')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

const setThemeNeumorphic = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#3000FF')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#3000FF')
  style.setProperty('--theme_notes_background_color', '#EEEEEF')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', '2px 2px 2px #bababa, -2px -2px 2px #ffffff')

  style.setProperty('--theme_link_color', '#3000FF')
  style.setProperty('--theme_link_background_color', '#EEEEEF')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'none')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', '2px 2px 2px #bababa, -2px -2px 2px #ffffff')
  style.setProperty('--theme_link_box_shadow_active', '2px 2px 2px #ffffff, -2px -2px 2px #bababa')
  style.setProperty('--theme_link_filter', 'none')

  style.setProperty('--theme_text_input_color', '#3000FF')
  style.setProperty('--theme_text_input_background_color', '#EEEEEF')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', '2px 2px 2px #bababa, -2px -2px 2px #ffffff')
  style.setProperty('--theme_text_input_box_shadow_active', '2px 2px 2px #ffffff, -2px -2px 2px #bababa')

  style.setProperty('--theme_button_color', '#EEEEEF')
  style.setProperty('--theme_button_background_color', '#3000FF')
  style.setProperty('--theme_button_box_shadow', '2px 2px 2px #bababa, -2px -2px 2px #ffffff')
  style.setProperty('--theme_button_box_shadow_active', '2px 2px 2px #ffffff, -2px -2px 2px #bababa')

  style.setProperty('--theme_icon_button_color', '#3000FF')
  style.setProperty('--theme_icon_button_background_color', '#EEEEEF')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', '2px 2px 2px #bababa, -2px -2px 2px #ffffff')
  style.setProperty('--theme_icon_button_color_down', '#3000FF')
  style.setProperty('--theme_icon_button_background_color_down', '#EEEEEF')
  style.setProperty('--theme_icon_button_box_shadow_down', '2px 2px 2px #ffffff, -2px -2px 2px #bababa')

  style.setProperty('--theme_background_color', '#EEEEEF')
  style.setProperty('--theme_background_color_menu_bar', '#EEEEEF')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #EEEEEF 0%, #AAAAEF 35%, #090979 100%)')
  style.setProperty('--theme_background_color_status_bar', '#EEEEEF')
  style.setProperty('--theme_background_color_button_down', '#EEEEEF')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#3000FF')
  style.setProperty('--theme_text_color_label', '#3000FF')
  style.setProperty('--theme_text_color_field', '#3000FF')
  style.setProperty('--theme_text_color_button_down', '#0055ff')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid white')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', '#555555')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', '5px 5px 5px #bababa, -5px -5px 5px #ffffff')
  style.setProperty('--theme_box_shadow_image_button', '5px 5px 5px #bababa, -5px -5px 5px #ffffff')
  style.setProperty('--theme_box_shadow_image_button_active', '5px 5px 5px #ffffff, -5px -5px 5px #bababa')
  style.setProperty('--theme_box_shadow_small', '3px 3px 3px #bababa, -3px -3px 3px #ffffff')
  style.setProperty('--theme_box_shadow_small_active', '2px 2px 2px #ffffff, -3px -3px 3px #bababa')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', 'rgba(0,51,153,0.3)')
  style.setProperty('--theme_secondary_power_set', 'rgba(153,0,0,0.3)')
  style.setProperty('--theme_pool_power_set', 'rgba(255,153,0,0.3)')
  style.setProperty('--theme_epic_power_set', 'rgba(153,0,0,0.3)')
  style.setProperty('--theme_inherent_power_set', 'rgba(51,102,0,0.3)')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

const setThemeNeumorphicDark = () => {
  const style = document.documentElement.style
  style.setProperty('--theme_label_color', '#7B68EE')
  style.setProperty('--theme_label_alt_color', '#000099')
  style.setProperty('--theme_label_disabled_color', '#999999')
  style.setProperty('--theme_label_background_color', 'transparent')
  style.setProperty('--theme_label_text_align', 'left')
  style.setProperty('--theme_label_overflow ', 'hidden')
  style.setProperty('--theme_label_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_label_small_font_size', 'small')
  style.setProperty('--theme_label_medium_font_size', 'medium')
  style.setProperty('--theme_label_large_font_size', 'large')

  style.setProperty('--theme_notes_color', '#7B68EE')
  style.setProperty('--theme_notes_background_color', '#242424')
  style.setProperty('--theme_notes_editor_color', '#555555')
  style.setProperty('--theme_notes_box_shadow', '2px 2px 2px #000000, -2px -2px 2px #7B68EE')

  style.setProperty('--theme_link_color', '#7B68EE')
  style.setProperty('--theme_link_background_color', '#242424')
  style.setProperty('--theme_link_text_align', 'center')
  style.setProperty('--theme_link_text_decoration', 'none')
  style.setProperty('--theme_link_overflow', 'hidden')
  style.setProperty('--theme_link_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_link_font_size', 'medium')
  style.setProperty('--theme_link_box_shadow', '2px 2px 2px #000000, -2px -2px 2px #7B68EE')
  style.setProperty('--theme_link_box_shadow_active', '2px 2px 2px #7B68EE, -2px -2px 2px #000000')
  style.setProperty('--theme_link_filter', 'none')

  style.setProperty('--theme_text_input_color', '#242424')
  style.setProperty('--theme_text_input_background_color', '#7B68EE')
  style.setProperty('--theme_text_input_text_align', 'left')
  style.setProperty('--theme_text_input_overflow', 'hidden')
  style.setProperty('--theme_text_input_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_text_input_font_size', 'medium')
  style.setProperty('--theme_text_input_box_shadow', '2px 2px 2px #000000, -2px -2px 2px #7B68EE')
  style.setProperty('--theme_text_input_box_shadow_active', '2px 2px 2px #7B68EE, -2px -2px 2px #000000')

  style.setProperty('--theme_button_color', '#242424')
  style.setProperty('--theme_button_background_color', '#7B68EE')
  style.setProperty('--theme_button_box_shadow', '2px 2px 2px #000000, -2px -2px 2px #7B68EE')
  style.setProperty('--theme_button_box_shadow_active', '2px 2px 2px #7B68EE, -2px -2px 2px #000000')

  style.setProperty('--theme_icon_button_color', '#7B68EE')
  style.setProperty('--theme_icon_button_background_color', '#242424')
  style.setProperty('--theme_icon_button_margin', '3px')
  style.setProperty('--theme_icon_button_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_icon_button_border_radius', '50%')
  style.setProperty('--theme_icon_button_box_shadow', '2px 2px 2px #000000, -2px -2px 2px #7B68EE')
  style.setProperty('--theme_icon_button_color_down', '#7B68EE')
  style.setProperty('--theme_icon_button_background_color_down', '#242424')
  style.setProperty('--theme_icon_button_box_shadow_down', '2px 2px 2px #7B68EE, -2px -2px 2px #000000')

  style.setProperty('--theme_background_color', '#242424')
  style.setProperty('--theme_background_color_menu_bar', '#242424')
  style.setProperty('--theme_background_image_menu_bar', 'linear-gradient(270deg, #242424 0%, #242455 35%, #242424 100%)')
  style.setProperty('--theme_background_color_status_bar', '#242424')
  style.setProperty('--theme_background_color_button_down', '#242424')
  style.setProperty('--theme_font_family', '"Roboto", sans-serif')
  style.setProperty('--theme_font_size_small', 'small')
  style.setProperty('--theme_font_size_medium', 'medium')
  style.setProperty('--theme_font_size_large', 'large')
  style.setProperty('--theme_text_align_title', 'left')
  style.setProperty('--theme_text_align_image_button', 'center')
  style.setProperty('--theme_text_align_label', 'left')
  style.setProperty('--theme_text_align_field', 'left')
  style.setProperty('--theme_text_color_image_button', '#7B68EE')
  style.setProperty('--theme_text_color_label', '#7B68EE')
  style.setProperty('--theme_text_color_field', '#7B68EE')
  style.setProperty('--theme_text_color_button_down', '#7B68EE')
  style.setProperty('--theme_text_color_image_button_disabled', '#999999')
  style.setProperty('--theme_text_color_label_disabled', '#999999')
  style.setProperty('--theme_text_color_field_disabled', '#999999')
  style.setProperty('--theme_text_color_slots_remaining', '#999999')
  style.setProperty('--theme_border_radius_image_button_image', '50%')
  style.setProperty('--theme_border_image_button_image', '2px solid black')
  style.setProperty('--theme_buton_text_color', '#EEEEEF')
  style.setProperty('--theme_buton_background_color', '#242424')
  style.setProperty('--theme_buton_text_color_disabled', '#999999')
  style.setProperty('--theme_buton_background_color_disabled', '#EEEEEF')
  style.setProperty('--theme_box_shadow_menu_bar', '5px 5px 5px #000000, -3px -3px 3px #7B68EE')
  style.setProperty('--theme_box_shadow_image_button', '5px 5px 5px #000000, -3px -3px 3px #7B68EE')
  style.setProperty('--theme_box_shadow_image_button_active', '5px 5px 5px #7B68EE, -3px -3px 3px #000000')
  style.setProperty('--theme_box_shadow_small', '3px 3px 3px #000000, -2px -2px 2px #7B68EE')
  style.setProperty('--theme_box_shadow_small_active', '2px 2px 2px #7B68EE, -3px -3px 3px #000000')
  style.setProperty('--theme_no_power_set', '#999999')
  style.setProperty('--theme_primary_power_set', '#003399')
  style.setProperty('--theme_secondary_power_set', '#990000')
  style.setProperty('--theme_pool_power_set', '#FF9900')
  style.setProperty('--theme_epic_power_set', '#FFFF66')
  style.setProperty('--theme_inherent_power_set', '#336600  ')
  style.setProperty('--theme_power_set_background_color', '#DDDDDD')
  style.setProperty('--theme_power_set_text_color', '#555555')
}

export { setThemeLight, setThemeDark, setThemeHero, setThemeVillian, setThemeGamma, setThemeNeumorphic, setThemeNeumorphicDark }
